### ISSUE TITLE
Clicking "Change" crashes or doesnt work

### ISSUE THREAD

**Issue by Noitidart** [Noitidart/NativeShot#31]
Affects v1.8 - Clicking "Change" on the options for "Quick save dir" doesn't work - sometimes causes crash of firefox.

**Comment by sojusnik** [comment]
Also observed under Firefox 47 on Ubuntu.

**Comment by Noitidart** [comment]
Thanks very much @sojusnik for this report. I am working as we speak on v1.9 which is a massive performance overhaul (on non-editor parts), it will address this issue. I hope to get it out in a couple of weeks.
