### ISSUE TITLE
Button does not appear in Firefox 49.0 und 50.0 after Start

### ISSUE THREAD

**Issue by Boersenfeger** [Noitidart/NativeShot#40]
Hi, unfortunately, the Button of Native Shot does not appear in Firefox 49.0 Developer and 50.0 Nightly after Firefox Start. It would be nice if this could be corrected in a future release. So far, only benefits a repeated installation of Native Shot.
No Problem in Firefox 47.0 und Firefox 48.0 Beta 
Thank you so much!
Greetz Bo

**Comment by Noitidart** [comment]
Thanks very much for this report I will look into this within a week. :)

**Comment by Boersenfeger** [comment]
Hi, any News about it?

**Comment by Noitidart** [comment]
Hey thanks for checking up. I fixed the issue. You can install the version from here - v1.9b.rev2 - https://github.com/Noitidart/NativeShot/tree/6c841d118c707dd9638f4ce36856b6adbfdf3516

I'm working on 1.9 release right now which is a big performance improvement (not in the editor but in the connections around it and the dashboard).

**Comment by Boersenfeger** [comment]
Wow, thanks... but I cant find the Download.
Please give me a working Link for your Beta-Version.
Thank you very much...

**Comment by Noitidart** [comment]
:)
Please try this, it is dev version so it has debug logging in it so performance is a bit reduced. Please rename to `.xpi` and then install to firefox.

[NativeShot v1.9b.rev2.zip](https://github.com/Noitidart/NativeShot/files/352912/NativeShot.v1.9b.rev2.zip)

**Comment by Boersenfeger** [comment]
Thanks, works for me....:-))
:+1:

**Comment by Noitidart** [comment]
Sweet! Thanks for confirmation :)

**Comment by Noitidart** [comment]
Just uploaded v1.9 release which as this fixed. It's pending AMO review. They won't let me review it myself haha
