### ISSUE TITLE
Complex Text Layout Problem in the dashboard

### ISSUE THREAD

**Issue by noureddin** [Noitidart/NativeShot#57]
Arabic letters are -mostly- connected to each other in the same word, unlike many other scripts (including Latin). In the dashboard, many words appear disconnected. In this screenshot (the history tab form the dashboard), the disconnected words are highlighted in red, and the normal, continuous words are highlighted in green.
![nativeshot](https://cloud.githubusercontent.com/assets/2486008/18246905/8a2d2b4a-7377-11e6-869b-30e8c0ec4df5.png)

**Comment by Noitidart** [comment]
Hey @noureddin I addressed this issue and the right to left issue (#58). I think only these 3 languages are connected: Arabic, Urdu, and Farsi. Do you know of any others?

Here is a build with Arabic locale and these fixes, if you can please try it out and provide feedback that would be superb! I'm real excited to give the whole Middle East an addon in their own language! :)

I attached a build of this version, please download it, rename from `.zip` to `.xpi` and then go to `about:debugging` and then "Load as temporary addon" and it should install. :)

[NativeShot-1.10b.rev9.zip](https://github.com/Noitidart/NativeShot/files/470706/NativeShot-1.10b.rev9.zip)

**Comment by noureddin** [comment]
Concerning only the direction and the disconnecting issues, this build is great and it solves both of them! It works very well with Arabic, so I can safely assume it will work well with Farsi, Urdu, and other languages that use an adapted Arabic alphabet, too.

Other RTL languages include Hebrew, which is written in disconnected letters (like Latin or Greek). And other CTL languages include most Indian languages, in which the letters are joined in the word, but they are LTR.

What else should I try, apart from these two issues?

**Comment by Noitidart** [comment]
Thank you very much @noureddin! No need to try anything else I think I resolve the other issue which was the mag/demag effect.

I don't have any support for the Indian languages but if someone provides those languages I'll make sure to check this connection issue. Thank you for this note!

no need to try anything more, you did so much! thank you! May you also please close issue #58 if you think it is resolved.

**Comment by noureddin** [comment]
You're the one to be thanked for your addons and your support, @Noitidart! I didn't do so much, in fact.

I've just closed the RTL issue (#58). Thank you!

**Comment by noureddin** [comment]
Hello again,

I'm sorry to comment on this closed issue. There is a little thing I noticed just now; it's not a real problem in most cases, but it could improve the user experience.

The quick save folder path (in the dashboard) is RTL when the language is Arabic. I think it's better to make it LTR even when the language uses an RTL script.

In the upper part of this image, the path is RTL, so it's `home/nour/` instead of `/home/nour` (cf. the lower part).
![Quick Save Folder path is RTL](https://cloud.githubusercontent.com/assets/2486008/18524452/1a33bfba-7ac1-11e6-9e8c-af60adee12e1.png)

**Comment by Noitidart** [comment]
Nooo problem, always welcome to post in closed issues. I really appreicate you taking the time to test this out! I'll fix that right now
