### ISSUE TITLE
Right-to-left Support

### ISSUE THREAD

**Issue by noureddin** [Noitidart/NativeShot#58]
Arabic is written from right to left, so LTR pages should be mirrored. The upper part of this screenshot shows the original history tab from the dashboard. The lower part shows it after reversing the page direction, which is much better for Arabic. Actually, it needs a little more tweaking than just that, but this step only is about half the solution.
![nativeshot-rtl](https://cloud.githubusercontent.com/assets/2486008/18248694/821fac60-7382-11e6-8cf6-ae9cd2e10c46.png)

**Comment by Noitidart** [comment]
Oops found an issue while testing it, the "magnify" effect when clicking on "View" of an image in the gallery does not follow correct starting points.

**Comment by Noitidart** [comment]
Fixed magnific for rtl. And also found a bug. Pressing escape while the image was zoomed in was not doing anything. It now closes it out.
