### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by stevepoppers** [Noitidart/NativeShot#59]
"status": false,
    "statusText": "failed-callbackset",
    "callbackSetName": "authorizeApp_imgur",
    "operation": "imgur-oauth-load"

I'm signed in and can upload to imgur site just fine, as well as upload anonymously. If there's a sign-in option in the addon, I can't find it.

**Comment by Noitidart** [comment]
This was an issue in v1.8 I uploaded v1.9 six days ago it is pending approval. If your browser doesn't yet force signing you can try it out from here - https://addons.mozilla.org/en-US/firefox/addon/nativeshot/versions/

Excuse the delay please. I really appreciate you posting this.

**Comment by Noitidart** [comment]
@stevepoppers how did v1.9 work out for you?

**Comment by Noitidart** [comment]
@stevepoppers v1.11 is out today please let me know how it works for you. If it's good we can close this issue.

**Comment by stevepoppers** [comment]
It's working! Excellent. Thanks.

**Comment by Noitidart** [comment]
Thank you @stevepoppers ! I have an update v1.13 coming out this week or next week. It drastically reduces the amount of times you need to reauthorize your oauth services. It also brings out the authorization management page. :)
