### ISSUE TITLE
stopped working since update

### ISSUE THREAD

**Issue by poirte** [Noitidart/NativeShot#63]
Since the update, the whole screen just goes gray and [esc] does nothing and the only way to get back to ffox is go to task bar and close native shot from there. I'd take a screen shot, but that i no longer possible with native shot installed

**Comment by Noitidart** [comment]
Oh shoot. Thanks for filing this report. This is a bad bug. Are you using a version of Firefox < 46?

I realized that my stuff is only working in Firefox 46 and up.

**Comment by Noitidart** [comment]
@poirte I think I fixed it. Can you please try this attached version. Github wouldn't let me upload `.xpi`. So I renamed it to `.zip` just to upload. Please download this but don't extract. Just rename it to `.xpi` and then go to `about:debugging` and then click "Load as temporary addon" and select this XPI.

[NativeShot-1.10b.rev13.zip](https://github.com/Noitidart/NativeShot/files/471015/NativeShot-1.10b.rev13.zip)

**Comment by Noitidart** [comment]
I have another version that fixes some more stuff. Will upload in 30 seconds

**Comment by Noitidart** [comment]
I made some more fixes may you please try this attached file, please remember rename to xpi and then install.
[NativeShot-1.10b.rev14.zip](https://github.com/Noitidart/NativeShot/files/472061/NativeShot-1.10b.rev14.zip)

**Comment by poirte** [comment]
Thanks this works fine now.

**Comment by Noitidart** [comment]
Thanks @poirte for being a user and reporting this! I upload v1.10 it should be approved in a few hours :)

**Comment by poirte** [comment]
Sorry, I was mistaken. It doesn't actually upload the image for me. It gets
to "initializes upload" but the image never uploads.

**Comment by Noitidart** [comment]
I reopened this. Which version did you use? Please try v1.10 from here - https://addons.mozilla.org/en-US/firefox/addon/nativeshot/versions/

**Comment by Noitidart** [comment]
@poirte may you please try the attached version I changed some more stuff which i think should fix it all. May you please also test all services like imgur, imgur anon, google drive, dropbox, searches, etc.

[NativeShot-v1.11b.rev2.zip](https://github.com/Noitidart/NativeShot/files/477345/NativeShot-v1.11b.rev2.zip)

**Comment by poirte** [comment]
Thanks, I was using FF v45. I tested with v45 and everything worked and it
uploaded to all of the options. Then I updated to v47 and it still works.

**Comment by Noitidart** [comment]
@poirte yay thank you! I will release it as v1.11 along with Bulgarian language support. May you please test the dashboard too?

**Comment by poirte** [comment]
dashboard seems to work fine. it has all my history and the options work

**Comment by Noitidart** [comment]
Woohoo thank you very much sir for being a user and contributor! Will upload to marketplace momentarily just testing out Bulgraian language.
