### ISSUE TITLE
RTL problem in Authorization page

### ISSUE THREAD

**Issue by noureddin** [Noitidart/NativeShot#67]
The new Authorization page needs to improve its support for right-to-left languages.

It's now like this:
![nativeshot-auth-ar](https://cloud.githubusercontent.com/assets/2486008/18708154/16b5c95a-8002-11e6-8f14-33e63b7ae492.png)

- The buttons should be on the other side, and
- they should have equal widths. Also,
- there should be some space between the text and the icons.

Compare the English version.
![nativeshot-auth-en](https://cloud.githubusercontent.com/assets/2486008/18708153/16839430-8002-11e6-9c86-9189c13fdc63.png)

**Comment by Noitidart** [comment]
Thanks for the catch i totally forgot to test this, will wrap this up today :)

**Comment by Noitidart** [comment]
@noureddin may you please test the attached, it has the fix.

[nativeshot-v1.12b.rev17.zip](https://github.com/Noitidart/NativeShot/files/484959/nativeshot-v1.12b.rev17.zip)

**Comment by noureddin** [comment]
Thanks for the quick fix, but I have a strange problem with this build!

![829](https://cloud.githubusercontent.com/assets/2486008/18711513/fd5b6878-8012-11e6-9502-9838662a795a.png)

Addons Manager:
![828](https://cloud.githubusercontent.com/assets/2486008/18711512/fd492032-8012-11e6-872e-d9ec707a263b.png)

And the BabelZilla build (with the Arabic locale) works fine.
![830](https://cloud.githubusercontent.com/assets/2486008/18711684/c49dcd68-8013-11e6-846d-c275d0008d74.png)

**Comment by Noitidart** [comment]
Oops try this one please
[nativeshot-v1.12b.rev17-2.zip](https://github.com/Noitidart/NativeShot/files/485061/nativeshot-v1.12b.rev17-2.zip)

**Comment by noureddin** [comment]
It works fine now, but a different problem has appeared! :D

![no translation](https://cloud.githubusercontent.com/assets/2486008/18714266/e02f522c-801d-11e6-852d-6020c28d3d13.png)

By the way, I improved the uninstalling string in the translation.

**Comment by Noitidart** [comment]
Oh shoot none of the Arabic strings are showing huh?
