### ISSUE TITLE
Not compitible with firefox 57.x 

### ISSUE THREAD

**Issue by ishah09** [Noitidart/NativeShot#77]
I am having firefox 57.0b8 (64-bit) version, Nativeshot is not compatible with it. Please check feasibility and make it compatible asap.

**Comment by Noitidart** [comment]
Thanks for being a user!! Firefox completely changed and it's not possible to make it using existing webext technology. I have to create it as a standalone app and then connect it to the browser. I started work on desktop version here - https://github.com/Noitidart/NativeShotDesktop

Duplicate topic - https://github.com/Noitidart/NativeShot/issues/75
